name: Frontend CI Pipeline

# Trigger the workflow on push or pull_request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Chromium
        run: sudo apt-get install -y chromium-browser

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.x"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          cd frontend
          npm install

      # Step 4: Run tests
      - name: Run tests
        run: |
          cd frontend
          npm test --watch=false --no-watch --no-progress --browsers=ChromeHeadless

      # Step 5: Build the application
      - name: Build the Angular project
        run: |
          cd frontend
          npm build
